swagger: "2.0"
info:
  version: 8.11.0
  title: "@fastify/swagger"
definitions: {}
paths:
  /clients/self:
    get:
      parameters:
        - type: string
          required: true
          in: header
          name: senacor-olb-client-id
        - format: email
          type: string
          required: true
          in: header
          name: senacor-olb-email
        - format: uuid
          type: string
          required: true
          in: header
          name: senacor-olb-partner-id
        - type: string
          required: true
          in: header
          name: user-agent
      responses:
        "200":
          description: Default Response
          schema:
            type: object
            properties:
              id:
                type: string
              firstName:
                type: string
              lastName:
                type: string
              permissions:
                type: object
                properties:
                  canSeeSubNavigationForPersonalInformation:
                    type: boolean
                required:
                  - canSeeSubNavigationForPersonalInformation
            required:
              - id
              - firstName
              - lastName
              - permissions
  /clients/self/security:
    get:
      parameters:
        - type: string
          required: true
          in: header
          name: senacor-olb-client-id
        - format: email
          type: string
          required: true
          in: header
          name: senacor-olb-email
        - format: uuid
          type: string
          required: true
          in: header
          name: senacor-olb-partner-id
      responses:
        "200":
          description: Default Response
          schema:
            type: object
            properties:
              clientId:
                type: string
              mobileTanNumber:
                type: string
              email:
                type: string
            required:
              - clientId
              - mobileTanNumber
              - email
  /clients/self/tax-information:
    get:
      parameters:
        - type: string
          required: true
          in: header
          name: senacor-olb-client-id
        - format: email
          type: string
          required: true
          in: header
          name: senacor-olb-email
        - format: uuid
          type: string
          required: true
          in: header
          name: senacor-olb-partner-id
        - type: string
          required: true
          in: header
          name: user-agent
      responses:
        "200":
          description: Default Response
          schema:
            type: object
            properties:
              taxId:
                type: string
              exemptionOrder:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                      - ACTIVE
                  totalExemptAmount:
                    type: object
                    properties:
                      currencyCode:
                        type: string
                      value:
                        type: number
                    required:
                      - currencyCode
                      - value
                  usedExemptAmount:
                    type: object
                    properties:
                      currencyCode:
                        type: string
                      value:
                        type: number
                    required:
                      - currencyCode
                      - value
                  validFrom:
                    format: date
                    type: string
                  validUntil:
                    format: date
                    type: string
                required:
                  - status
                  - totalExemptAmount
                  - validFrom
                  - validUntil
              nonAssessmentCertificate:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                      - ACTIVE
                  validFrom:
                    format: date
                    type: string
                  validUntil:
                    format: date
                    type: string
                required:
                  - status
                  - validFrom
                  - validUntil
            required:
              - taxId
  /clients/self/email/validation:
    post:
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              newEmail:
                format: email
                type: string
            required:
              - newEmail
      responses:
        "200":
          description: Default Response
          schema:
            type: object
            properties:
              challengeDataJwt:
                type: string
            required:
              - challengeDataJwt
  /clients/self/email:
    patch:
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              newEmail:
                format: email
                type: string
            required:
              - newEmail
      responses:
        "200":
          description: Default Response
  /clients/self/mobile-phone/validation:
    post:
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              newMobilePhone:
                type: string
                pattern: ^([+]\d{2})(\d{4})(\d{3,8})$
            required:
              - newMobilePhone
      responses:
        "200":
          description: Default Response
          schema:
            type: object
            properties:
              challengeDataJwt:
                type: string
            required:
              - challengeDataJwt
  /clients/self/mobile-phone:
    patch:
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              newMobilePhone:
                type: string
                pattern: ^([+]\d{2})(\d{4})(\d{3,8})$
            required:
              - newMobilePhone
      responses:
        "200":
          description: Default Response
  /clients/self/addresses/main:
    get:
      responses:
        "200":
          description: Default Response
          schema:
            type: object
            properties:
              company:
                type: string
              street:
                type: string
              streetNumber:
                type: string
              doorNumber:
                type: string
              zipCode:
                type: string
              city:
                type: string
              state:
                type: string
              deliveryInstruction:
                type: string
            required:
              - street
              - streetNumber
              - zipCode
              - city
              - state
  /clients/self/addresses/validation:
    post:
      parameters:
        - name: body
          in: body
          schema:
            additionalProperties: false
            type: object
            properties:
              company:
                type: string
              street:
                type: string
              streetNumber:
                type: string
              doorNumber:
                type: string
              zipCode:
                type: string
              city:
                type: string
              state:
                type: string
              deliveryInstruction:
                type: string
            required:
              - street
              - streetNumber
              - zipCode
              - city
              - state
      responses:
        "200":
          description: Default Response
          schema:
            type: object
            properties:
              challengeDataJwt:
                type: string
            required:
              - challengeDataJwt
  /clients/self/addresses:
    patch:
      parameters:
        - name: body
          in: body
          schema:
            additionalProperties: false
            type: object
            properties:
              company:
                type: string
              street:
                type: string
              streetNumber:
                type: string
              doorNumber:
                type: string
              zipCode:
                type: string
              city:
                type: string
              state:
                type: string
              deliveryInstruction:
                type: string
            required:
              - street
              - streetNumber
              - zipCode
              - city
              - state
        - type: string
          required: true
          in: header
          name: senacor-olb-client-id
        - format: email
          type: string
          required: true
          in: header
          name: senacor-olb-email
        - format: uuid
          type: string
          required: true
          in: header
          name: senacor-olb-partner-id
        - type: string
          required: true
          in: header
          name: transaction-signing-token
        - type: string
          required: true
          in: header
          name: user-agent
      responses:
        "200":
          description: Default Response
  /clients/self/federal-states:
    get:
      responses:
        "200":
          description: Default Response
          schema:
            type: object
            properties:
              federalStates:
                type: array
                items:
                  type: string
            required:
              - federalStates
  /clients/self/personal-information:
    get:
      parameters:
        - type: string
          required: true
          in: header
          name: senacor-olb-client-id
        - format: email
          type: string
          required: true
          in: header
          name: senacor-olb-email
        - format: uuid
          type: string
          required: true
          in: header
          name: senacor-olb-partner-id
        - type: string
          required: true
          in: header
          name: user-agent
      responses:
        "200":
          description: Default Response
          schema:
            type: object
            properties:
              clientId:
                type: string
              firstName:
                type: string
              lastName:
                type: string
              mobilePhone:
                type: string
              homePhone:
                type: string
              dateOfBirth:
                type: string
              salutation:
                type: string
              title:
                type: string
              emailAddress:
                type: string
              clientAddress:
                type: object
                properties:
                  addressType:
                    type: string
                  streetNumber:
                    type: string
                  zipCode:
                    type: string
                  country:
                    type: string
                  city:
                    type: string
                  street:
                    type: string
                  state:
                    type: string
                required:
                  - addressType
                  - streetNumber
                  - zipCode
                  - country
                  - city
                  - street
                  - state
              taxId:
                type: string
              permissions:
                type: object
                properties:
                  canChangePersonalInformation:
                    type: boolean
                  canUploadDocument:
                    type: boolean
                required:
                  - canChangePersonalInformation
                  - canUploadDocument
            required:
              - clientId
              - firstName
              - lastName
              - mobilePhone
              - homePhone
              - dateOfBirth
              - salutation
              - title
              - emailAddress
              - clientAddress
              - taxId
              - permissions
