swagger: "2.0"
info:
  version: 8.12.0
  title: "@fastify/swagger"
definitions: {}
paths:
  /partners/self/fixed-deposits/{productId}:
    get:
      parameters:
        - format: uuid
          type: string
          required: true
          in: path
          name: productId
        - type: string
          required: true
          in: header
          name: senacor-olb-client-id
        - format: email
          type: string
          required: true
          in: header
          name: senacor-olb-email
        - format: uuid
          type: string
          required: true
          in: header
          name: senacor-olb-partner-id
        - type: string
          required: true
          in: header
          name: user-agent
      responses:
        "200":
          description: Default Response
          schema:
            type: object
            properties:
              id:
                type: string
              balance:
                type: object
                properties:
                  value:
                    type: number
                  currencyCode:
                    type: string
                required:
                  - value
                  - currencyCode
              interestRate:
                type: number
              accountNumber:
                type: string
              investmentValue:
                type: number
              investmentPeriod:
                multipleOf: 1
                type: number
              investmentPeriodUnit:
                type: string
                enum:
                  - MONTH
              referenceAccount:
                type: object
                properties:
                  iban:
                    type: string
                  accountOwner:
                    type: string
                  bank:
                    type: string
                required:
                  - iban
                  - accountOwner
                  - bank
              conditions:
                type: object
                properties:
                  depositAmount:
                    type: object
                    properties:
                      value:
                        type: number
                      currencyCode:
                        type: string
                    required:
                      - value
                      - currencyCode
                  interestYield:
                    type: object
                    properties:
                      value:
                        type: number
                      currencyCode:
                        type: string
                    required:
                      - value
                      - currencyCode
                required:
                  - depositAmount
                  - interestYield
              permissions:
                type: object
                properties:
                  canSeeTransactions:
                    type: boolean
                  canWrite:
                    type: boolean
                required:
                  - canSeeTransactions
                  - canWrite
            required:
              - id
              - balance
              - interestRate
              - accountNumber
              - investmentValue
              - investmentPeriod
              - investmentPeriodUnit
              - referenceAccount
              - permissions
  /partners/self/fixed-deposits:
    get:
      parameters:
        - type: string
          required: true
          in: header
          name: senacor-olb-client-id
        - format: email
          type: string
          required: true
          in: header
          name: senacor-olb-email
        - format: uuid
          type: string
          required: true
          in: header
          name: senacor-olb-partner-id
        - type: string
          required: true
          in: header
          name: user-agent
      responses:
        "200":
          description: Default Response
          schema:
            type: object
            properties:
              deposits:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    accountNumber:
                      type: string
                    balance:
                      type: object
                      properties:
                        value:
                          type: number
                        currencyCode:
                          type: string
                      required:
                        - value
                        - currencyCode
                    interestRate:
                      type: number
                    readable:
                      type: boolean
                  required:
                    - id
                    - accountNumber
                    - balance
                    - interestRate
                    - readable
              totalBalance:
                type: object
                properties:
                  value:
                    type: number
                  currencyCode:
                    type: string
                required:
                  - value
                  - currencyCode
              permissions:
                type: object
                properties:
                  canCreateFixedDeposit:
                    type: boolean
                required:
                  - canCreateFixedDeposit
            required:
              - deposits
              - totalBalance
              - permissions
  /partners/self/fixed-deposits/{productId}/transactions:
    get:
      parameters:
        - format: uuid
          type: string
          required: true
          in: path
          name: productId
        - type: string
          required: true
          in: header
          name: senacor-olb-client-id
        - format: email
          type: string
          required: true
          in: header
          name: senacor-olb-email
        - format: uuid
          type: string
          required: true
          in: header
          name: senacor-olb-partner-id
        - type: string
          required: true
          in: header
          name: user-agent
      responses:
        "200":
          description: Default Response
          schema:
            type: object
            properties:
              transactions:
                type: array
                items:
                  type: object
                  properties:
                    executionDate:
                      format: date-time
                      type: string
                    purpose:
                      type: string
                    amount:
                      type: object
                      properties:
                        value:
                          type: number
                        currencyCode:
                          type: string
                      required:
                        - value
                        - currencyCode
                  required:
                    - executionDate
                    - purpose
                    - amount
            required:
              - transactions
  /partners/self/fixed-deposits/{productId}/reference-account/validation:
    post:
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              accountOwner:
                minLength: 1
                maxLength: 70
                pattern: ^[a-zA-Z0-9\s]+$
                type: string
              bankName:
                minLength: 1
                maxLength: 70
                pattern: ^[a-zA-Z0-9\s]+$
                type: string
              iban:
                type: string
              bic:
                minLength: 8
                maxLength: 11
                pattern: ^[A-Z]{4}[A-Z]{2}[A-Z0-9]{2}(?:[A-Z0-9]{3})?$
                type: string
            required:
              - accountOwner
              - bankName
              - iban
              - bic
        - format: uuid
          type: string
          required: true
          in: path
          name: productId
        - type: string
          required: true
          in: header
          name: senacor-olb-client-id
        - format: email
          type: string
          required: true
          in: header
          name: senacor-olb-email
        - format: uuid
          type: string
          required: true
          in: header
          name: senacor-olb-partner-id
        - type: string
          required: true
          in: header
          name: user-agent
      responses:
        "200":
          description: Default Response
          schema:
            type: object
            properties:
              challengeDataJwt:
                type: string
            required:
              - challengeDataJwt
  /partners/self/fixed-deposits/{productId}/reference-account:
    patch:
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              accountOwner:
                type: string
              bankName:
                type: string
              iban:
                type: string
              bic:
                type: string
            required:
              - accountOwner
              - bankName
              - iban
              - bic
        - format: uuid
          type: string
          required: true
          in: path
          name: productId
        - type: string
          required: true
          in: header
          name: senacor-olb-client-id
        - format: email
          type: string
          required: true
          in: header
          name: senacor-olb-email
        - format: uuid
          type: string
          required: true
          in: header
          name: senacor-olb-partner-id
        - type: string
          required: true
          in: header
          name: transaction-signing-token
        - type: string
          required: true
          in: header
          name: user-agent
      responses:
        "200":
          description: Default Response
